/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as LiquidityRouteImport } from './routes/liquidity'
import { Route as FaucetRouteImport } from './routes/faucet'
import { Route as FarmRouteImport } from './routes/farm'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminFarmRouteImport } from './routes/admin-farm'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DNameRouteImport } from './routes/d.$name'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidityRoute = LiquidityRouteImport.update({
  id: '/liquidity',
  path: '/liquidity',
  getParentRoute: () => rootRouteImport,
} as any)
const FaucetRoute = FaucetRouteImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmRoute = FarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFarmRoute = AdminFarmRouteImport.update({
  id: '/admin-farm',
  path: '/admin-farm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DNameRoute = DNameRouteImport.update({
  id: '/d/$name',
  path: '/d/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-farm': typeof AdminFarmRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/brand': typeof BrandRoute
  '/domains': typeof DomainsRoute
  '/farm': typeof FarmRoute
  '/faucet': typeof FaucetRoute
  '/liquidity': typeof LiquidityRoute
  '/pools': typeof PoolsRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/d/$name': typeof DNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-farm': typeof AdminFarmRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/brand': typeof BrandRoute
  '/domains': typeof DomainsRoute
  '/farm': typeof FarmRoute
  '/faucet': typeof FaucetRoute
  '/liquidity': typeof LiquidityRoute
  '/pools': typeof PoolsRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/d/$name': typeof DNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-farm': typeof AdminFarmRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/brand': typeof BrandRoute
  '/domains': typeof DomainsRoute
  '/farm': typeof FarmRoute
  '/faucet': typeof FaucetRoute
  '/liquidity': typeof LiquidityRoute
  '/pools': typeof PoolsRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/d/$name': typeof DNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-farm'
    | '/ai'
    | '/analytics'
    | '/brand'
    | '/domains'
    | '/farm'
    | '/faucet'
    | '/liquidity'
    | '/pools'
    | '/portfolio'
    | '/sitemap.xml'
    | '/swap'
    | '/d/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-farm'
    | '/ai'
    | '/analytics'
    | '/brand'
    | '/domains'
    | '/farm'
    | '/faucet'
    | '/liquidity'
    | '/pools'
    | '/portfolio'
    | '/sitemap.xml'
    | '/swap'
    | '/d/$name'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-farm'
    | '/ai'
    | '/analytics'
    | '/brand'
    | '/domains'
    | '/farm'
    | '/faucet'
    | '/liquidity'
    | '/pools'
    | '/portfolio'
    | '/sitemap.xml'
    | '/swap'
    | '/d/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminFarmRoute: typeof AdminFarmRoute
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BrandRoute: typeof BrandRoute
  DomainsRoute: typeof DomainsRoute
  FarmRoute: typeof FarmRoute
  FaucetRoute: typeof FaucetRoute
  LiquidityRoute: typeof LiquidityRoute
  PoolsRoute: typeof PoolsRoute
  PortfolioRoute: typeof PortfolioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SwapRoute: typeof SwapRoute
  DNameRoute: typeof DNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidity': {
      id: '/liquidity'
      path: '/liquidity'
      fullPath: '/liquidity'
      preLoaderRoute: typeof LiquidityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet': {
      id: '/faucet'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof FaucetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm': {
      id: '/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-farm': {
      id: '/admin-farm'
      path: '/admin-farm'
      fullPath: '/admin-farm'
      preLoaderRoute: typeof AdminFarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$name': {
      id: '/d/$name'
      path: '/d/$name'
      fullPath: '/d/$name'
      preLoaderRoute: typeof DNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminFarmRoute: AdminFarmRoute,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  BrandRoute: BrandRoute,
  DomainsRoute: DomainsRoute,
  FarmRoute: FarmRoute,
  FaucetRoute: FaucetRoute,
  LiquidityRoute: LiquidityRoute,
  PoolsRoute: PoolsRoute,
  PortfolioRoute: PortfolioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SwapRoute: SwapRoute,
  DNameRoute: DNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
