export const aiExecutionControllerAbi = [
  { inputs: [{ name: "_aiExecutor", type: "address" }], stateMutability: "nonpayable", type: "constructor" },
  { anonymous: false, inputs: [{ indexed: true, name: "oldExecutor", type: "address" }, { indexed: true, name: "newExecutor", type: "address" }], name: "ExecutorChanged", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "previousOwner", type: "address" }, { indexed: true, name: "newOwner", type: "address" }], name: "OwnershipTransferred", type: "event" },
  { anonymous: false, inputs: [], name: "Paused", type: "event" },
  { anonymous: false, inputs: [], name: "Unpaused", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "caller", type: "address" }, { indexed: false, name: "data", type: "bytes" }, { indexed: false, name: "timestamp", type: "uint256" }], name: "UpkeepPerformed", type: "event" },
  { inputs: [], name: "aiExecutor", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "bytes" }], name: "checkUpkeep", outputs: [{ name: "upkeepNeeded", type: "bool" }, { name: "performData", type: "bytes" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "user", type: "address" }, { name: "index", type: "uint256" }], name: "getUserUpkeepLog", outputs: [{ name: "data", type: "bytes" }, { name: "timestamp", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "user", type: "address" }], name: "getUserUpkeepLogCount", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "owner", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "pause", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "paused", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "performData", type: "bytes" }], name: "performUpkeep", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_newExecutor", type: "address" }], name: "setAIExecutor", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "newOwner", type: "address" }], name: "transferOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "unpause", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "", type: "address" }, { name: "", type: "uint256" }], name: "userUpkeepLogs", outputs: [{ name: "data", type: "bytes" }, { name: "timestamp", type: "uint256" }], stateMutability: "view", type: "function" },
] as const;
