export const aiGuardrailAbi = [
  { inputs: [{ name: "_maxPriceImpactBps", type: "uint256" }, { name: "_dailyLimit", type: "uint256" }], stateMutability: "nonpayable", type: "constructor" },
  { anonymous: false, inputs: [{ indexed: true, name: "token", type: "address" }, { indexed: false, name: "price", type: "uint256" }], name: "ReferencePriceUpdated", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "token", type: "address" }, { indexed: false, name: "status", type: "bool" }], name: "TokenWhitelisted", type: "event" },
  { inputs: [{ name: "token", type: "address" }, { name: "amount", type: "uint256" }], name: "checkDailyVolume", outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "token", type: "address" }, { name: "tradeAmount", type: "uint256" }], name: "checkMaxPriceImpact", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "expected", type: "uint256" }, { name: "actual", type: "uint256" }], name: "checkSlippage", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "dailyLimit", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "address" }], name: "dailyVolume", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "token", type: "address" }], name: "isTokenWhitelisted", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "address" }], name: "lastReset", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "maxPriceImpactBps", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "owner", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "address" }], name: "referencePrice", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "_limit", type: "uint256" }], name: "setDailyLimit", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_bps", type: "uint256" }], name: "setMaxPriceImpactBps", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "token", type: "address" }, { name: "price", type: "uint256" }], name: "setReferencePrice", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "token", type: "address" }, { name: "status", type: "bool" }], name: "setTokenWhitelist", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "", type: "address" }], name: "whitelist", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
] as const;
