export const mockVrfAbi = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "requestId", type: "uint256" },
      { indexed: true, internalType: "address", name: "requester", type: "address" },
    ],
    name: "RandomnessRequested",
    type: "event",
  },
  {
    inputs: [
      { internalType: "uint32", name: "", type: "uint32" },
      { internalType: "uint256", name: "userSeed", type: "uint256" },
    ],
    name: "requestRandomWords",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [{ internalType: "address", name: "_casino", type: "address" }], name: "setCasino", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "newOwner", type: "address" }], name: "transferOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "casino", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "requestIdCounter", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
] as const;

const betTuple = [
  { internalType: "address", name: "player", type: "address" },
  { internalType: "uint256", name: "amount", type: "uint256" },
  { internalType: "uint8", name: "game", type: "uint8" },
  { internalType: "uint8", name: "choice", type: "uint8" },
  { internalType: "uint256", name: "requestId", type: "uint256" },
  { internalType: "uint8", name: "status", type: "uint8" },
  { internalType: "uint256", name: "payout", type: "uint256" },
  { internalType: "uint256", name: "timestamp", type: "uint256" },
] as const;

export const casinoAbi = [
  { inputs: [{ internalType: "address", name: "_vrf", type: "address" }], stateMutability: "nonpayable", type: "constructor" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "player", type: "address" },
      { indexed: false, internalType: "uint256", name: "requestId", type: "uint256" },
      { indexed: false, internalType: "uint8", name: "game", type: "uint8" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "uint8", name: "choice", type: "uint8" },
    ],
    name: "BetPlaced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "requestId", type: "uint256" },
      { indexed: true, internalType: "address", name: "player", type: "address" },
      { indexed: false, internalType: "bool", name: "won", type: "bool" },
      { indexed: false, internalType: "uint256", name: "payout", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "randomResult", type: "uint256" },
    ],
    name: "BetSettled",
    type: "event",
  },
  { anonymous: false, inputs: [{ indexed: false, internalType: "uint256", name: "newEdge", type: "uint256" }], name: "HouseEdgeUpdated", type: "event" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "uint256", name: "minBet", type: "uint256" }, { indexed: false, internalType: "uint256", name: "maxBet", type: "uint256" }], name: "LimitsUpdated", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "provider", type: "address" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }], name: "LiquidityDeposited", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "to", type: "address" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }], name: "LiquidityWithdrawn", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "previousOwner", type: "address" }, { indexed: true, internalType: "address", name: "newOwner", type: "address" }], name: "OwnershipTransferred", type: "event" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }], name: "Paused", type: "event" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }], name: "Unpaused", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "player", type: "address" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }], name: "PayoutSent", type: "event" },

  { inputs: [], name: "depositLiquidity", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "requestId", type: "uint256" }, { internalType: "uint256[]", name: "randomWords", type: "uint256[]" }], name: "fulfillRandomWords", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "pause", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "unpause", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint8", name: "choice", type: "uint8" }], name: "playCoinFlip", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [{ internalType: "uint8", name: "choice", type: "uint8" }], name: "playDice", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [{ internalType: "uint8", name: "choice", type: "uint8" }], name: "playHighLow", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [{ internalType: "uint8", name: "choice", type: "uint8" }], name: "playRoulette", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [{ internalType: "uint8", name: "choice", type: "uint8" }], name: "playRPS", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_min", type: "uint256" }, { internalType: "uint256", name: "_max", type: "uint256" }], name: "setBetLimits", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_edge", type: "uint256" }], name: "setHouseEdge", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "_vrf", type: "address" }], name: "setVRF", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "newOwner", type: "address" }], name: "transferOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "withdrawAll", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }], name: "withdrawLiquidity", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "withdrawPending", outputs: [], stateMutability: "nonpayable", type: "function" },
  { stateMutability: "payable", type: "receive" },

  { inputs: [{ internalType: "uint256", name: "", type: "uint256" }], name: "bets", outputs: betTuple, stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "requestId", type: "uint256" }], name: "getBet", outputs: [{ components: betTuple, internalType: "struct FinalCasinoNoOZ.Bet", name: "", type: "tuple" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "getContractBalance", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "houseEdge", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "maxBet", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "minBet", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "paused", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "", type: "address" }], name: "pendingWithdrawals", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "vrfCoordinator", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
] as const;
