export const farmAbi = [
  { inputs: [{ internalType: "contract IERC20", name: "_stakingToken", type: "address" }, { internalType: "uint256", name: "_allocPoint", type: "uint256" }], name: "addPool", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_pid", type: "uint256" }], name: "claimReward", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_pid", type: "uint256" }, { internalType: "uint256", name: "_amount", type: "uint256" }], name: "deposit", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_pid", type: "uint256" }], name: "emergencyWithdraw", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_pid", type: "uint256" }, { internalType: "uint256", name: "_allocPoint", type: "uint256" }], name: "setAllocPoint", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_rewardPerBlock", type: "uint256" }], name: "setRewardPerBlock", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "contract IERC20", name: "_rewardToken", type: "address" }], name: "setRewardToken", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_startBlock", type: "uint256" }], name: "setStartBlock", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_pid", type: "uint256" }], name: "updatePool", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_pid", type: "uint256" }, { internalType: "uint256", name: "_amount", type: "uint256" }], name: "withdraw", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_pid", type: "uint256" }, { internalType: "address", name: "_user", type: "address" }], name: "pendingReward", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "", type: "uint256" }], name: "poolInfo", outputs: [
    { internalType: "contract IERC20", name: "stakingToken", type: "address" },
    { internalType: "uint256", name: "allocPoint", type: "uint256" },
    { internalType: "uint256", name: "lastRewardBlock", type: "uint256" },
    { internalType: "uint256", name: "accRewardPerShare", type: "uint256" },
    { internalType: "uint256", name: "totalStaked", type: "uint256" },
  ], stateMutability: "view", type: "function" },
  { inputs: [], name: "poolLength", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "rewardPerBlock", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "rewardToken", outputs: [{ internalType: "contract IERC20", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "startBlock", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "totalAllocPoint", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "", type: "uint256" }, { internalType: "address", name: "", type: "address" }], name: "userInfo", outputs: [
    { internalType: "uint256", name: "amount", type: "uint256" },
    { internalType: "uint256", name: "rewardDebt", type: "uint256" },
  ], stateMutability: "view", type: "function" },
  { anonymous: false, inputs: [{ indexed: true, name: "user", type: "address" }, { indexed: true, name: "pid", type: "uint256" }, { indexed: false, name: "amount", type: "uint256" }], name: "Deposit", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "user", type: "address" }, { indexed: true, name: "pid", type: "uint256" }, { indexed: false, name: "amount", type: "uint256" }], name: "Withdraw", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "user", type: "address" }, { indexed: true, name: "pid", type: "uint256" }, { indexed: false, name: "amount", type: "uint256" }], name: "ClaimReward", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, name: "user", type: "address" }, { indexed: true, name: "pid", type: "uint256" }, { indexed: false, name: "amount", type: "uint256" }], name: "EmergencyWithdraw", type: "event" },
] as const;
